title: "Só é Natal se for partilhado"
author:
    name: Ekino
    email: 'ekinopt@gmail.com'
metadata:
    description: 'Só é Natal se for partilhado'

team:
    - Arena
    - Fuel
    - Havas Media
    - HSE
    - Havas
